version: '3.8'

services:
  budgets:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./app/.env.dev
    depends_on:
      - budgets-db
  budgets-db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=budgets
      - POSTGRES_PASSWORD=budgets
      - POSTGRES_DB=budgets_dev

volumes:
  postgres_data: