# Generated by Django 4.1.3 on 2022-11-05 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_expense_income_budgetmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="members",
            field=models.ManyToManyField(
                related_name="user_budgets", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="BudgetMember",
        ),
    ]
